<div id="optMenu" style="background-color:#FFF; border:#CCC solid 1px; position:absolute;display:none;">
    <div class="menuRow" style="width:100%;" onMouseOver="over(this);" onMouseOut="out(this);">
        <div style="width:23px; padding:3px; background-color:#E9EEEE;border:none; float:left;"></div>
        <div style="border:none; float:left; padding-top:2px;margin-left:5px; font:normal;">View</div>
    </div>
    <div class="menuRow" style="width:100%; " onMouseOver="over(this);" onMouseOut="out(this);">
        <div style="width:23px; padding:3px;  background-color:#E9EEEE;border:none; float:left;"><img class="icon" src="images/edit.gif" alt="Click to edit"></div>
        <div style="border:none; float:left; padding-top:2px;margin-left:5px; font:normal;">Edit</div>
    </div>
    
    <div class="menuRow" style="width:100%; " onMouseOver="over(this);" onMouseOut="out(this);">
        <div style="width:23px; padding:3px;  background-color:#E9EEEE;border:none; float:left;"><img class="icon" src="images/duplicate.gif" alt="Click to Copy"></div>
        <div style="border:none; float:left; padding-top:2px;margin-left:5px; font:normal;">Copy</div>
    </div>


    <div class="menuRow" style="width:100%; " onMouseOver="over(this);" onMouseOut="out(this);">
        <div style="width:23px; padding:3px; background-color:#E9EEEE;border:none; float:left;"><img class="icon" src="images/delitem.gif" alt="Click to delete"></div>
        <div style="border:none; float:left;padding-top:2px; margin-left:5px; font:normal;" >Delete</div>
    </div>
    <div class="menuRow" style="width:100%;" onMouseOver="over(this);" onMouseOut="out(this);">
        <div style="width:23px; padding:3px; background-color:#E9EEEE;border:none; float:left;"><img class="icon" src="images/backIcon.gif" alt="Click to Cancel"></div>
        <div style="border:none; float:left; padding-top:2px;margin-left:5px; font:normal;">Cancel</div>
    </div>
</div>